# Generated by Django 5.1.7 on 2025-03-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="required_skills",
        ),
        migrations.AddField(
            model_name="job",
            name="required_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
