# Generated by Django 5.1.7 on 2025-03-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboards", "0002_remove_job_required_skills_job_required_skills"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feeditem",
            name="jobboards_f_posted__224715_idx",
        ),
        migrations.RemoveIndex(
            model_name="feeditem",
            name="jobboards_f_is_rele_813cf6_idx",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="company_profile",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="is_relevant",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="location",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="posted_date",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="technologies",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="title",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="url",
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="guid",
            field=models.CharField(help_text="Unique ID from source", max_length=255),
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="is_processed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this item has been processed into a Job",
            ),
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="raw_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Original data from source"
            ),
        ),
    ]
