# Generated by Django 5.1.7 on 2025-03-20 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("jobboards", "0004_alter_jobsearchquery_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="job",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                default="4621443b-290d-44e7-90f9-72651ef872db",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobboard_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("source", "source_id", "user")},
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["user", "status"], name="jobboards_j_user_id_8722f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["user", "relevance_score"],
                name="jobboards_j_user_id_ea48a4_idx",
            ),
        ),
    ]
