# Generated by Django 5.1.7 on 2025-03-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboards", "0005_alter_job_unique_together_job_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_currency",
            field=models.CharField(blank=True, default="USD", max_length=3, null=True),
        ),
    ]
