# Generated by Django 5.1.7 on 2025-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboards", "0006_alter_job_salary_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="url",
            field=models.TextField(),
        ),
    ]
