# Generated by Django 5.0.12 on 2025-03-02 22:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Company Name")),
                ("website", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "employee_count_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "employee_count_max",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "headquarters_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "headquarters_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "stock_symbol",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("researching", "Researching"),
                            ("target", "Target Company"),
                            ("contacting", "In Contact"),
                            ("applied", "Applied To"),
                            ("interviewing", "Interviewing With"),
                            ("rejected", "Rejected By"),
                            ("not_interested", "Not Interested In"),
                        ],
                        default="researching",
                        max_length=20,
                    ),
                ),
                ("ai_analysis", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
            },
        ),
        migrations.CreateModel(
            name="CompanyRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_target",
                    models.BooleanField(
                        default=False,
                        help_text="Mark industries you're targeting in your job search",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Industries",
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.CreateModel(
            name="CompanyIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_associations",
                        to="companies.companyprofile",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="companies.industry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Industries",
                "unique_together": {("company", "industry")},
            },
        ),
        migrations.CreateModel(
            name="CompanyTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="companies.companyprofile",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="companies.technology",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Technologies",
                "unique_together": {("company", "technology")},
            },
        ),
        migrations.CreateModel(
            name="UserCompanyAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "influence_level",
                    models.IntegerField(
                        default=1,
                        help_text="Scale of 1-10 indicating this person's influence in hiring decisions",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "relationship_status",
                    models.CharField(
                        choices=[
                            ("to_contact", "To Contact"),
                            ("contacted", "Contacted"),
                            ("responded", "Responded"),
                            ("meeting_scheduled", "Meeting Scheduled"),
                            ("connected", "Connected"),
                            ("not_responsive", "Not Responsive"),
                        ],
                        default="to_contact",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("last_contact_date", models.DateTimeField(blank=True, null=True)),
                ("next_contact_date", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnel",
                        to="companies.companyprofile",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_associations",
                        to="companies.companyrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_associations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Association",
                "verbose_name_plural": "Company Associations",
                "unique_together": {("user", "company", "job_title")},
            },
        ),
    ]
