# Generated by Django 5.1.7 on 2025-03-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="status",
        ),
    ]
