# Generated by Django 5.1.7 on 2025-03-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_remove_companyprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="careers_page_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="employee_sentiment_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="funding_rounds",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="funding_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bootstrapped", "Bootstrapped"),
                    ("seed", "Seed"),
                    ("a", "Series A"),
                    ("b", "Series B"),
                    ("c", "Series C"),
                    ("d", "Series D"),
                    ("e", "Series E"),
                    ("f", "Series F"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="github_repos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="github_stars",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="glassdoor_rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="indeed_rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="last_funding_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="last_sentiment_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="latest_funding_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="latest_funding_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="linkedin_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="open_jobs_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="open_source_contribution_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="recent_news",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="sentiment_data_points",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="social_media_handles",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="total_funding",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
