# Generated by Django 5.1.7 on 2025-03-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_companyprofile_careers_page_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyResearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_logs",
                        to="companies.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Research Log",
                "verbose_name_plural": "Company Research Logs",
            },
        ),
        migrations.CreateModel(
            name="CompanyResearchReferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_references",
                        to="companies.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Research Reference",
                "verbose_name_plural": "Company Research References",
            },
        ),
    ]
