# Generated by Django 5.1.7 on 2025-03-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companyresearchlog_companyresearchreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="headquarters_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
