# Generated by Django 5.0.12 on 2025-03-06 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_posts",
                to="companies.companyprofile",
            ),
        ),
    ]
