# Generated by Django 5.1.7 on 2025-04-12 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_contactmethodtype_usercontactmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bluesky_handle",
            field=models.CharField(
                blank=True, max_length=145, null=True, verbose_name="Bluesky Handle"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="github_handle",
            field=models.CharField(
                blank=True, max_length=145, null=True, verbose_name="GitHub Handle"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_handle",
            field=models.CharField(
                blank=True, max_length=145, null=True, verbose_name="LinkedIn Handle"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="substack_url",
            field=models.CharField(
                blank=True, max_length=145, null=True, verbose_name="Substack URL"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_handle",
            field=models.CharField(
                blank=True, max_length=145, null=True, verbose_name="Twitter Handle"
            ),
        ),
        migrations.CreateModel(
            name="UserAdditionalEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "email")},
            },
        ),
        migrations.CreateModel(
            name="UserPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "phone_number")},
            },
        ),
    ]
