# Generated by Django 5.1.7 on 2025-04-12 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_bluesky_handle_user_github_handle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alternate_names",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Alternate Names"
            ),
        ),
        migrations.CreateModel(
            name="UserSourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("article", "Article"),
                            ("blog", "Blog Post"),
                            ("mention", "Mention"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("discovery_date", models.DateTimeField(auto_now_add=True)),
                ("relevance_score", models.FloatField(default=0.5)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "url")},
            },
        ),
    ]
