# Generated by Django 5.1.7 on 2025-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_companyprofile_headquarters_state"),
        ("users", "0004_user_alternate_names_usersourcelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="associated_users",
                through="companies.UserCompanyAssociation",
                to="companies.companyprofile",
            ),
        ),
    ]
